// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4sXK_ym_qUBD-h4eXMxQ0KoBbuSZ_sk',
    appId: '1:321168222580:web:d959e4833d3a55038c6421',
    messagingSenderId: '321168222580',
    projectId: 'inicio-flu-f15af',
    authDomain: 'inicio-flu-f15af.firebaseapp.com',
    storageBucket: 'inicio-flu-f15af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWe5aC-hW8JJmqWP_2teGWKib-ZZPqjwM',
    appId: '1:321168222580:android:6af998f6677d28148c6421',
    messagingSenderId: '321168222580',
    projectId: 'inicio-flu-f15af',
    storageBucket: 'inicio-flu-f15af.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-4sXK_ym_qUBD-h4eXMxQ0KoBbuSZ_sk',
    appId: '1:321168222580:web:13fdbecc5588e8a48c6421',
    messagingSenderId: '321168222580',
    projectId: 'inicio-flu-f15af',
    authDomain: 'inicio-flu-f15af.firebaseapp.com',
    storageBucket: 'inicio-flu-f15af.firebasestorage.app',
  );
}
